import { LLMProvider, LLMMessage, LLMResponse, LLMProviderConfig } from './types';
import { APP_CONFIG } from '../../config/constants';

export class GeminiProvider implements LLMProvider {
  readonly type = 'gemini' as const;
  private apiKey: string;
  private model: string;
  private baseUrl = APP_CONFIG.llm.gemini.baseUrl;

  constructor(config: LLMProviderConfig) {
    this.apiKey = config.apiKey || APP_CONFIG.llm.gemini.apiKey;
    this.model = config.model || APP_CONFIG.llm.gemini.defaultModel;
    
    if (!this.apiKey) {
      console.warn('[Gemini] No API key configured. Gemini will not be available.');
    }
  }

  async isAvailable(): Promise<boolean> {
    if (!this.apiKey) return false;
    
    try {
      const response = await fetch(
        `${this.baseUrl}/models?key=${this.apiKey}`,
        {
          method: 'GET',
          signal: AbortSignal.timeout(5000),
        }
      );
      
      return response.ok;
    } catch (error) {
      console.warn('[Gemini] Not available:', error);
      return false;
    }
  }

  async chat(messages: LLMMessage[], options?: {
    temperature?: number;
    maxTokens?: number;
  }): Promise<LLMResponse> {
    if (!this.apiKey) {
      throw new Error('Gemini API key not configured');
    }

    try {
      const { contents, systemInstruction } = this.formatMessages(messages);
      
      const payload: any = {
        contents,
        generationConfig: {
          temperature: options?.temperature ?? 0.7,
          maxOutputTokens: options?.maxTokens ?? 2048,
          topP: 0.95,
          topK: 40,
        },
      };

      if (systemInstruction) {
        payload.systemInstruction = {
          parts: [{ text: systemInstruction }],
        };
      }

      const response = await fetch(
        `${this.baseUrl}/models/${this.model}:generateContent?key=${this.apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(payload),
        }
      );

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(
          `Gemini API error (${response.status}): ${errorData.error?.message || response.statusText}`
        );
      }

      const data = await response.json();

      if (!data.candidates || data.candidates.length === 0) {
        throw new Error('No response generated by Gemini');
      }

      const content = data.candidates[0]?.content?.parts?.[0]?.text || '';
      const tokensUsed = data.usageMetadata?.totalTokenCount || 0;

      return {
        content,
        model: this.model,
        provider: 'gemini',
        tokensUsed,
      };
    } catch (error) {
      console.error('[Gemini] Chat error:', error);
      throw new Error(`Gemini request failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  private formatMessages(messages: LLMMessage[]): { contents: any[]; systemInstruction?: string } {
    let systemInstruction = '';
    const contents: any[] = [];
    
    for (const msg of messages) {
      if (msg.role === 'system') {
        systemInstruction = systemInstruction ? `${systemInstruction}\n\n${msg.content}` : msg.content;
      } else {
        contents.push({
          role: msg.role === 'assistant' ? 'model' : 'user',
          parts: [{ text: msg.content }],
        });
      }
    }

    // Ensure there is at least one content part
    if (contents.length === 0 && systemInstruction) {
      contents.push({
        role: 'user',
        parts: [{ text: 'Please proceed based on your system instructions.' }],
      });
    }
    
    return { contents, systemInstruction: systemInstruction || undefined };
  }
}
